# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393
#' @useDynLib testrcpp
#' @importFrom Rcpp sourceCpp
NULL

convolve_cpp <- function(a, b) {
    .Call(`_testrcpp_convolve_cpp`, a, b)
}

